module.exports = (function () {

  // N/search Module Members

  var search = function() {};

  // Object

  var Column = function() {};

  var Filter = function() {};

  var Page = function() {};

  var PagedData = function() {};

  var Result = function() {};

  var ResultSet = function() {};

  var Search = function() {};

  var Setting = function() {};

  search.prototype.Column = Column;

  search.prototype.Filter = Filter;

  search.prototype.Page = Page;

  search.prototype.PagedData = PagedData;

  search.prototype.Result = Result;

  search.prototype.ResultSet = ResultSet;

  search.prototype.Search = Search;

  search.prototype.Setting = Setting;

  // Method

  search.prototype.create = function(options) {};

  search.prototype.create.promise = function(options) {};

  search.prototype.createColumn = function(options) {};

  search.prototype.createFilter = function(options) {};

  search.prototype.createSetting = function(options) {};

  search.prototype["delete"] = function(options) {};

  search.prototype["delete"].promise = function(options) {};

  search.prototype.duplicates = function(options) {};

  search.prototype.duplicates.promise = function(options) {};

  search.prototype.global = function(options) {};

  search.prototype.global.promise = function(options) {};

  search.prototype.load = function(options) {};

  search.prototype.load.promise = function(options) {};

  search.prototype.lookupFields = function(options) {};

  search.prototype.lookupFields.promise = function(options) {};

  // Column Object Methods

  Column.prototype.setWhenOrderedBy = function(options) {};

  // Page Object Methods

  Page.prototype.next = function() {};

  Page.prototype.next.promise = function() {};

  Page.prototype.prev = function() {};

  Page.prototype.prev.promise = function() {};

  // PagedData Object Members

  PagedData.prototype.fetch = function() {};

  PagedData.prototype.fetch.promise = function() {};

  // Result Object Methods

  Result.prototype.getText = function(options) {};

  Result.prototype.getValue = function(options) {};

  // ResultSet Object Methods

  ResultSet.prototype.each = function(callback) {};

  ResultSet.prototype.each.promise = function(callback) {};

  ResultSet.prototype.getRange = function(options) {};

  ResultSet.prototype.getRange.promise = function(options) {};

  // Search Object Methods

  Search.prototype.run = function() {};

  Search.prototype.runPaged = function() {};

  Search.prototype.runPaged.promise = function() {};

  Search.prototype.save = function() {};

  Search.prototype.save.promise = function() {};

  // Enum

  function Operator() {
    this.AFTER = "AFTER";
    this.ALLOF = "ALLOF";
    this.ANY = "ANY";
    this.ANYOF = "ANYOF";
    this.BEFORE = "BEFORE";
    this.BETWEEN = "BETWEEN";
    this.CONTAINS = "CONTAINS";
    this.DOESNOTCONTAIN = "DOESNOTCONTAIN";
    this.DOESNOTSTARTWITH = "DOESNOTSTARTWITH";
    this.EQUALTO = "EQUALTO";
    this.GREATERTHAN = "GREATERTHAN";
    this.GREATERTHANOREQUALTO = "GREATERTHANOREQUALTO";
    this.HASKEYWORDS = "HASKEYWORDS";
    this.IS = "IS";
    this.ISEMPTY = "ISEMPTY";
    this.ISNOT = "ISNOT";
    this.ISNOTEMPTY = "ISNOTEMPTY";
    this.LESSTHAN = "LESSTHAN";
    this.LESSTHANOREQUALTO = "LESSTHANOREQUALTO";
    this.NONEOF = "NONEOF";
    this.NOTAFTER = "NOTAFTER";
    this.NOTALLOF = "NOTALLOF";
    this.NOTBEFORE = "NOTBEFORE";
    this.NOTBETWEEN = "NOTBETWEEN";
    this.NOTEQUALTO = "NOTEQUALTO";
    this.NOTGREATERTHAN = "NOTGREATERTHAN";
    this.NOTGREATERTHANOREQUALTO = "NOTGREATERTHANOREQUALTO";
    this.NOTLESSTHAN = "NOTLESSTHAN";
    this.NOTLESSTHANOREQUALTO = "NOTLESSTHANOREQUALTO";
    this.NOTON = "NOTON";
    this.NOTONORAFTER = "NOTONORAFTER";
    this.NOTONORBEFORE = "NOTONORBEFORE";
    this.NOTWITHIN = "NOTWITHIN";
    this.ON = "ON";
    this.ONORAFTER = "ONORAFTER";
    this.ONORBEFORE = "ONORBEFORE";
    this.STARTSWITH = "STARTSWITH";
    this.WITHIN = "WITHIN";
  }

  function Sort() {
    this.ASC = "ASC";
    this.DESC = "DESC";
    this.NONE = "NONE";
  }

  function Summary() {
    this.GROUP = "GROUP";
    this.COUNT = "COUNT";
    this.SUM = "SUM";
    this.AVG = "AVG";
    this.MIN = "MIN";
    this.MAX = "MAX";
  }

  function Type() {
    this.ACCOUNT = "ACCOUNT";
    this.ACCOUNTING_BOOK = "ACCOUNTING_BOOK";
    this.ACCOUNTING_CONTEXT = "ACCOUNTING_CONTEXT";
    this.ACCOUNTING_PERIOD = "ACCOUNTING_PERIOD";
    this.ACTIVITY = "ACTIVITY";
    this.ADV_INTER_COMPANY_JOURNAL_ENTRY = "ADV_INTER_COMPANY_JOURNAL_ENTRY";
    this.AGGR_FIN_DAT = "AGGR_FIN_DAT";
    this.ALLOC_RECOMMENDATION_DEMAND = "ALLOC_RECOMMENDATION_DEMAND";
    this.ALLOC_RECOMMENDATION_DETAIL = "ALLOC_RECOMMENDATION_DETAIL";
    this.AMORTIZATION_SCHEDULE = "AMORTIZATION_SCHEDULE";
    this.AMORTIZATION_TEMPLATE = "AMORTIZATION_TEMPLATE";
    this.ASSEMBLY_BUILD = "ASSEMBLY_BUILD";
    this.ASSEMBLY_ITEM = "ASSEMBLY_ITEM";
    this.ASSEMBLY_UNBUILD = "ASSEMBLY_UNBUILD";
    this.AUTHENTICATE_DEVICE_INPUT = "AUTHENTICATE_DEVICE_INPUT";
    this.BALANCE_TRX_BY_SEGMENTS = "BALANCE_TRX_BY_SEGMENTS";
    this.BALANCING_DETAIL = "BALANCING_DETAIL";
    this.BALANCING_RESULT = "BALANCING_RESULT";
    this.BALANCING_TRANSACTION = "BALANCING_TRANSACTION";
    this.BILLING_ACCOUNT = "BILLING_ACCOUNT";
    this.BILLING_ACCOUNT_BILL_CYCLE = "BILLING_ACCOUNT_BILL_CYCLE";
    this.BILLING_ACCOUNT_BILL_REQUEST = "BILLING_ACCOUNT_BILL_REQUEST";
    this.BILLING_CLASS = "BILLING_CLASS";
    this.BILLING_RATE_CARD = "BILLING_RATE_CARD";
    this.BILLING_REVENUE_EVENT = "BILLING_REVENUE_EVENT";
    this.BILLING_SCHEDULE = "BILLING_SCHEDULE";
    this.BIN = "BIN";
    this.BIN_ITEM_BALANCE = "BIN_ITEM_BALANCE";
    this.BIN_TRANSFER = "BIN_TRANSFER";
    this.BIN_WORKSHEET = "BIN_WORKSHEET";
    this.BLANKET_PURCHASE_ORDER = "BLANKET_PURCHASE_ORDER";
    this.BOM = "BOM";
    this.BOM_REVISION = "BOM_REVISION";
    this.BONUS = "BONUS";
    this.BONUS_TYPE = "BONUS_TYPE";
    this.BUDGET_EXCHANGE_RATE = "BUDGET_EXCHANGE_RATE";
    this.BULK_OWNERSHIP_TRANSFER = "BULK_OWNERSHIP_TRANSFER";
    this.BUNDLE_INSTALLATION_SCRIPT = "BUNDLE_INSTALLATION_SCRIPT";
    this.CALENDAR_EVENT = "CALENDAR_EVENT";
    this.CAMPAIGN = "CAMPAIGN";
    this.CARDHOLDER_AUTHENTICATION = "CARDHOLDER_AUTHENTICATION";
    this.CARDHOLDER_AUTHENTICATION_EVENT = "CARDHOLDER_AUTHENTICATION_EVENT";
    this.CASH_REFUND = "CASH_REFUND";
    this.CASH_SALE = "CASH_SALE";
    this.CHALLENGE_SHOPPER_INPUT = "CHALLENGE_SHOPPER_INPUT";
    this.CHARGE = "CHARGE";
    this.CHARGE_RULE = "CHARGE_RULE";
    this.CHECK = "CHECK";
    this.CLASSIFICATION = "CLASSIFICATION";
    this.CLIENT_SCRIPT = "CLIENT_SCRIPT";
    this.CMS_CONTENT = "CMS_CONTENT";
    this.CMS_CONTENT_TYPE = "CMS_CONTENT_TYPE";
    this.CMS_PAGE = "CMS_PAGE";
    this.COM_SEARCH_BOOST = "COM_SEARCH_BOOST";
    this.COM_SEARCH_BOOST_TYPE = "COM_SEARCH_BOOST_TYPE";
    this.COM_SEARCH_GROUP_SYN = "COM_SEARCH_GROUP_SYN";
    this.COM_SEARCH_ONE_WAY_SYN = "COM_SEARCH_ONE_WAY_SYN";
    this.COMMERCE_CATEGORY = "COMMERCE_CATEGORY";
    this.COMMERCE_SEARCH_ACTIVITY_DATA = "COMMERCE_SEARCH_ACTIVITY_DATA";
    this.COMPETITOR = "COMPETITOR";
    this.CONSOLIDATED_EXCHANGE_RATE = "CONSOLIDATED_EXCHANGE_RATE";
    this.CONTACT = "CONTACT";
    this.CONTACT_CATEGORY = "CONTACT_CATEGORY";
    this.CONTACT_ROLE = "CONTACT_ROLE";
    this.COST_CATEGORY = "COST_CATEGORY";
    this.COUPON_CODE = "COUPON_CODE";
    this.CREDIT_CARD_CHARGE = "CREDIT_CARD_CHARGE";
    this.CREDIT_CARD_REFUND = "CREDIT_CARD_REFUND";
    this.CREDIT_MEMO = "CREDIT_MEMO";
    this.CROSSCHARGEABLE = "CROSSCHARGEABLE";
    this.CURRENCY = "CURRENCY";
    this.CURRENCY_EXCHANGE_RATE = "CURRENCY_EXCHANGE_RATE";
    this.CUSTOMER = "CUSTOMER";
    this.CUSTOMER_CATEGORY = "CUSTOMER_CATEGORY";
    this.CUSTOMER_DEPOSIT = "CUSTOMER_DEPOSIT";
    this.CUSTOMER_MESSAGE = "CUSTOMER_MESSAGE";
    this.CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT";
    this.CUSTOMER_PAYMENT_AUTHORIZATION = "CUSTOMER_PAYMENT_AUTHORIZATION";
    this.CUSTOMER_REFUND = "CUSTOMER_REFUND";
    this.CUSTOMER_STATUS = "CUSTOMER_STATUS";
    this.CUSTOMER_SUBSIDIARY_RELATIONSHIP = "CUSTOMER_SUBSIDIARY_RELATIONSHIP";
    this.CUSTOM_PURCHASE = "CUSTOM_PURCHASE";
    this.CUSTOM_RECORD = "CUSTOM_RECORD";
    this.CUSTOM_SALE = "CUSTOM_SALE";
    this.CUSTOM_TRANSACTION = "CUSTOM_TRANSACTION";
    this.DELETED_RECORD = "DELETED_RECORD";
    this.DEPARTMENT = "DEPARTMENT";
    this.DEPOSIT = "DEPOSIT";
    this.DEPOSIT_APPLICATION = "DEPOSIT_APPLICATION";
    this.DESCRIPTION_ITEM = "DESCRIPTION_ITEM";
    this.DISCOUNT_ITEM = "DISCOUNT_ITEM";
    this.DOWNLOAD_ITEM = "DOWNLOAD_ITEM";
    this.EMPLOYEE = "EMPLOYEE";
    this.EMPLOYEE_CHANGE_REQUEST = "EMPLOYEE_CHANGE_REQUEST";
    this.EMPLOYEE_CHANGE_REQUEST_TYPE = "EMPLOYEE_CHANGE_REQUEST_TYPE";
    this.EMPLOYEE_CHANGE_TYPE = "EMPLOYEE_CHANGE_TYPE";
    this.EMPLOYEE_PAYROLL_ITEM = "EMPLOYEE_PAYROLL_ITEM";
    this.EMPLOYEE_STATUS = "EMPLOYEE_STATUS";
    this.END_TO_END_TIME = "END_TO_END_TIME";
    this.ENTITY = "ENTITY";
    this.ENTITY_ACCOUNT_MAPPING = "ENTITY_ACCOUNT_MAPPING";
    this.ESTIMATE = "ESTIMATE";
    this.EXPENSE_AMORTIZATION_EVENT = "EXPENSE_AMORTIZATION_EVENT";
    this.EXPENSE_AMORT_PLAN_AND_SCHEDULE = "EXPENSE_AMORT_PLAN_AND_SCHEDULE";
    this.EXPENSE_CATEGORY = "EXPENSE_CATEGORY";
    this.EXPENSE_PLAN = "EXPENSE_PLAN";
    this.EXPENSE_REPORT = "EXPENSE_REPORT";
    this.FAIR_VALUE_PRICE = "FAIR_VALUE_PRICE";
    this.FIN_RPT_AGGREGATE_F_R = "FIN_RPT_AGGREGATE_F_R";
    this.FINANCIAL_INSTITUTION = "FINANCIAL_INSTITUTION";
    this.FIXED_AMOUNT_PROJECT_REVENUE_RULE = "FIXED_AMOUNT_PROJECT_REVENUE_RULE";
    this.FOLDER = "FOLDER";
    this.FULFILLMENT_REQUEST = "FULFILLMENT_REQUEST";
    this.GATEWAY_NOTIFICATION = "GATEWAY_NOTIFICATION";
    this.GENERIC_RESOURCE = "GENERIC_RESOURCE";
    this.GIFT_CERTIFICATE = "GIFT_CERTIFICATE";
    this.GIFT_CERTIFICATE_ITEM = "GIFT_CERTIFICATE_ITEM";
    this.GLOBAL_ACCOUNT_MAPPING = "GLOBAL_ACCOUNT_MAPPING";
    this.GLOBAL_INVENTORY_RELATIONSHIP = "GLOBAL_INVENTORY_RELATIONSHIP";
    this.GL_LINES_AUDIT_LOG = "GL_LINES_AUDIT_LOG";
    this.GL_NUMBERING_SEQUENCE = "GL_NUMBERING_SEQUENCE";
    this.GOAL = "GOAL";
    this.INBOUND_SHIPMENT = "INBOUND_SHIPMENT";
    this.INSTALLMENT = "INSTALLMENT";
    this.INTER_COMPANY_JOURNAL_ENTRY = "INTER_COMPANY_JOURNAL_ENTRY";
    this.INTER_COMPANY_TRANSFER_ORDER = "INTER_COMPANY_TRANSFER_ORDER";
    this.INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT";
    this.INVENTORY_BALANCE = "INVENTORY_BALANCE";
    this.INVENTORY_COST_REVALUATION = "INVENTORY_COST_REVALUATION";
    this.INVENTORY_COUNT = "INVENTORY_COUNT";
    this.INVENTORY_DEMAND = "INVENTORY_DEMAND";
    this.INVENTORY_DETAIL = "INVENTORY_DETAIL";
    this.INVENTORY_ITEM = "INVENTORY_ITEM";
    this.INVENTORY_NUMBER = "INVENTORY_NUMBER";
    this.INVENTORY_NUMBER_BIN = "INVENTORY_NUMBER_BIN";
    this.INVENTORY_NUMBER_ITEM = "INVENTORY_NUMBER_ITEM";
    this.INVENTORY_STATUS = "INVENTORY_STATUS";
    this.INVENTORY_STATUS_CHANGE = "INVENTORY_STATUS_CHANGE";
    this.INVENTORY_STATUS_LOCATION = "INVENTORY_STATUS_LOCATION";
    this.INVENTORY_TRANSFER = "INVENTORY_TRANSFER";
    this.INVOICE = "INVOICE";
    this.INVOICE_GROUP = "INVOICE_GROUP";
    this.INVT_NUMBER_ITEM_BALANCE = "INVT_NUMBER_ITEM_BALANCE";
    this.ISSUE = "ISSUE";
    this.ITEM = "ITEM";
    this.ITEM_ACCOUNT_MAPPING = "ITEM_ACCOUNT_MAPPING";
    this.ITEM_BIN_NUMBER = "ITEM_BIN_NUMBER";
    this.ITEM_COLLECTION = "ITEM_COLLECTION";
    this.ITEM_COLLECTION_ITEM_MAP = "ITEM_COLLECTION_ITEM_MAP";
    this.ITEM_DEMAND_PLAN = "ITEM_DEMAND_PLAN";
    this.ITEM_FULFILLMENT = "ITEM_FULFILLMENT";
    this.ITEM_GROUP = "ITEM_GROUP";
    this.ITEM_LOCATION_CONFIGURATION = "ITEM_LOCATION_CONFIGURATION";
    this.ITEM_PROCESS_FAMILY = "ITEM_PROCESS_FAMILY";
    this.ITEM_PROCESS_GROUP = "ITEM_PROCESS_GROUP";
    this.ITEM_RECEIPT = "ITEM_RECEIPT";
    this.ITEM_REVISION = "ITEM_REVISION";
    this.ITEM_SUPPLY_PLAN = "ITEM_SUPPLY_PLAN";
    this.JOB = "JOB";
    this.JOB_STATUS = "JOB_STATUS";
    this.JOB_TYPE = "JOB_TYPE";
    this.JOURNAL_ENTRY = "JOURNAL_ENTRY";
    this.KIT_ITEM = "KIT_ITEM";
    this.LABOR_BASED_PROJECT_REVENUE_RULE = "LABOR_BASED_PROJECT_REVENUE_RULE";
    this.LABOR_CATEGORY = "LABOR_CATEGORY";
    this.LABOR_COST_CARD = "LABOR_COST_CARD";
    this.LABOR_COST_CARD_ITEM = "LABOR_COST_CARD_ITEM";
    this.LABOR_COST_ELEMENT = "LABOR_COST_ELEMENT";
    this.LEAD = "LEAD";
    this.LOCATION = "LOCATION";
    this.LOT_NUMBERED_ASSEMBLY_ITEM = "LOT_NUMBERED_ASSEMBLY_ITEM";
    this.LOT_NUMBERED_INVENTORY_ITEM = "LOT_NUMBERED_INVENTORY_ITEM";
    this.MANUFACTURING_COST_TEMPLATE = "MANUFACTURING_COST_TEMPLATE";
    this.MANUFACTURING_OPERATION_TASK = "MANUFACTURING_OPERATION_TASK";
    this.MANUFACTURING_ROUTING = "MANUFACTURING_ROUTING";
    this.MAP_REDUCE_SCRIPT = "MAP_REDUCE_SCRIPT";
    this.MARKUP_ITEM = "MARKUP_ITEM";
    this.MASSUPDATE_SCRIPT = "MASSUPDATE_SCRIPT";
    this.MEM_DOC = "MEM_DOC";
    this.MERCHANDISE_HIERARCHY_LEVEL = "MERCHANDISE_HIERARCHY_LEVEL";
    this.MERCHANDISE_HIERARCHY_NODE = "MERCHANDISE_HIERARCHY_NODE";
    this.MERCHANDISE_HIERARCHY_VERSION = "MERCHANDISE_HIERARCHY_VERSION";
    this.MESSAGE = "MESSAGE";
    this.MFG_PLANNED_TIME = "MFG_PLANNED_TIME";
    this.NEXUS = "NEXUS";
    this.NON_INVENTORY_ITEM = "NON_INVENTORY_ITEM";
    this.NOTE = "NOTE";
    this.NOTE_TYPE = "NOTE_TYPE";
    this.OPPORTUNITY = "OPPORTUNITY";
    this.ORDER_TYPE = "ORDER_TYPE";
    this.OTHER_CHARGE_ITEM = "OTHER_CHARGE_ITEM";
    this.OTHER_NAME = "OTHER_NAME";
    this.OTHER_NAME_CATEGORY = "OTHER_NAME_CATEGORY";
    this.PARTNER = "PARTNER";
    this.PARTNER_CATEGORY = "PARTNER_CATEGORY";
    this.PAYCHECK = "PAYCHECK";
    this.PAYCHECK_JOURNAL = "PAYCHECK_JOURNAL";
    this.PAYMENT_EVENT = "PAYMENT_EVENT";
    this.PAYMENT_INSTRUMENT = "PAYMENT_INSTRUMENT";
    this.PAYMENT_ITEM = "PAYMENT_ITEM";
    this.PAYMENT_METHOD = "PAYMENT_METHOD";
    this.PAYMENT_OPTION = "PAYMENT_OPTION";
    this.PAYMENT_RESULT_PREVIEW = "PAYMENT_RESULT_PREVIEW";
    this.PAYROLL_SETUP = "PAYROLL_SETUP";
    this.PAYROLL_ITEM = "PAYROLL_ITEM";
    this.PCT_COMPLETE_PROJECT_REVENUE_RULE = "PCT_COMPLETE_PROJECT_REVENUE_RULE";
    this.PERFORMANCE_METRIC = "PERFORMANCE_METRIC";
    this.PERFORMANCE_REVIEW = "PERFORMANCE_REVIEW";
    this.PERFORMANCE_REVIEW_SCHEDULE = "PERFORMANCE_REVIEW_SCHEDULE";
    this.PERIOD_END_JOURNAL = "PERIOD_END_JOURNAL";
    this.PERMISSION = "PERMISSION";
    this.PHONE_CALL = "PHONE_CALL";
    this.PICK_STRATEGY = "PICK_STRATEGY";
    this.PICK_TASK = "PICK_TASK";
    this.PLANNED_ORDER = "PLANNED_ORDER";
    this.PLANNING_ITEM_CATEGORY = "PLANNING_ITEM_CATEGORY";
    this.PLANNING_ITEM_GROUP = "PLANNING_ITEM_GROUP";
    this.PLANNING_RULE_GROUP = "PLANNING_RULE_GROUP";
    this.PORTLET = "PORTLET";
    this.PRICE_BOOK = "PRICE_BOOK";
    this.PRICE_LEVEL = "PRICE_LEVEL";
    this.PRICE_PLAN = "PRICE_PLAN";
    this.PRICING = "PRICING";
    this.PRICING_GROUP = "PRICING_GROUP";
    this.PROJECT_EXPENSE_TYPE = "PROJECT_EXPENSE_TYPE";
    this.PROJECT_IC_CHARGE_REQUEST = "PROJECT_IC_CHARGE_REQUEST";
    this.PROJECT_TASK = "PROJECT_TASK";
    this.PROJECT_TEMPLATE = "PROJECT_TEMPLATE";
    this.PROMISING_SETUP = "PROMISING_SETUP";
    this.PROMOTION_CODE = "PROMOTION_CODE";
    this.PROSPECT = "PROSPECT";
    this.PURCHASE_CONTRACT = "PURCHASE_CONTRACT";
    this.PURCHASE_ORDER = "PURCHASE_ORDER";
    this.PURCHASE_REQUISITION = "PURCHASE_REQUISITION";
    this.RECENT_RECORD = "RECENT_RECORD";
    this.RES_ALLOCATION_TIME_OFF_CONFLICT = "RES_ALLOCATION_TIME_OFF_CONFLICT";
    this.RESOURCE_ALLOCATION = "RESOURCE_ALLOCATION";
    this.RESTLET = "RESTLET";
    this.RETURN_AUTHORIZATION = "RETURN_AUTHORIZATION";
    this.REVENUE_ARRANGEMENT = "REVENUE_ARRANGEMENT";
    this.REVENUE_COMMITMENT = "REVENUE_COMMITMENT";
    this.REVENUE_COMMITMENT_REVERSAL = "REVENUE_COMMITMENT_REVERSAL";
    this.REVENUE_PLAN = "REVENUE_PLAN";
    this.REV_REC_PLAN_AND_SCHEDULE = "REV_REC_PLAN_AND_SCHEDULE";
    this.REV_REC_SCHEDULE = "REV_REC_SCHEDULE";
    this.REV_REC_TEMPLATE = "REV_REC_TEMPLATE";
    this.ROLE = "ROLE";
    this.S_C_M_PREDICTED_RISKS = "S_C_M_PREDICTED_RISKS";
    this.S_C_M_PREDICTION_TRAIN_HISTORY = "S_C_M_PREDICTION_TRAIN_HISTORY";
    this.SALES_ORDER = "SALES_ORDER";
    this.SALES_ROLE = "SALES_ROLE";
    this.SALES_TAX_ITEM = "SALES_TAX_ITEM";
    this.SAVED_SEARCH = "SAVED_SEARCH";
    this.SCHEDULED_SCRIPT = "SCHEDULED_SCRIPT";
    this.SCHEDULED_SCRIPT_INSTANCE = "SCHEDULED_SCRIPT_INSTANCE";
    this.SCRIPT_DEPLOYMENT = "SCRIPT_DEPLOYMENT";
    this.SERIALIZED_ASSEMBLY_ITEM = "SERIALIZED_ASSEMBLY_ITEM";
    this.SERIALIZED_INVENTORY_ITEM = "SERIALIZED_INVENTORY_ITEM";
    this.SERVICE_ITEM = "SERVICE_ITEM";
    this.SHIP_ITEM = "SHIP_ITEM";
    this.SHOPPING_CART = "SHOPPING_CART";
    this.SOLUTION = "SOLUTION";
    this.STATE = "STATE";
    this.STATISTICAL_JOURNAL_ENTRY = "STATISTICAL_JOURNAL_ENTRY";
    this.STORE_PICKUP_FULFILLMENT = "STORE_PICKUP_FULFILLMENT";
    this.SUBSCRIPTION = "SUBSCRIPTION";
    this.SUBSCRIPTION_CHANGE_ORDER = "SUBSCRIPTION_CHANGE_ORDER";
    this.SUBSCRIPTION_LINE = "SUBSCRIPTION_LINE";
    this.SUBSCRIPTION_LINE_REVISION = "SUBSCRIPTION_LINE_REVISION";
    this.SUBSCRIPTION_PLAN = "SUBSCRIPTION_PLAN";
    this.SUBSCRIPTION_RENEWAL_HISTORY = "SUBSCRIPTION_RENEWAL_HISTORY";
    this.SUBSIDIARY = "SUBSIDIARY";
    this.SUBTOTAL_ITEM = "SUBTOTAL_ITEM";
    this.SUITELET = "SUITELET";
    this.SUITE_SCRIPT_DETAIL = "SUITE_SCRIPT_DETAIL";
    this.SUPPLY_CHAIN_SNAPSHOT = "SUPPLY_CHAIN_SNAPSHOT";
    this.SUPPLY_CHAIN_SNAPSHOT_DETAILS = "SUPPLY_CHAIN_SNAPSHOT_DETAILS";
    this.SUPPLY_CHANGE_ORDER = "SUPPLY_CHANGE_ORDER";
    this.SUPPLY_PLAN_DEFINITION = "SUPPLY_PLAN_DEFINITION";
    this.SUPPORT_CASE = "SUPPORT_CASE";
    this.SYSTEM_NOTE = "SYSTEM_NOTE";
    this.TASK = "TASK";
    this.TAX_DETAIL = "TAX_DETAIL";
    this.TAX_GROUP = "TAX_GROUP";
    this.TAX_PERIOD = "TAX_PERIOD";
    this.TAX_TYPE = "TAX_TYPE";
    this.TERM = "TERM";
    this.TIMESHEET_APPROVAL = "TIMESHEET_APPROVAL";
    this.TIME_APPROVAL = "TIME_APPROVAL";
    this.TIME_BILL = "TIME_BILL";
    this.TIME_ENTRY = "TIME_ENTRY";
    this.TIME_OFF_CHANGE = "TIME_OFF_CHANGE";
    this.TIME_OFF_PLAN = "TIME_OFF_PLAN";
    this.TIME_OFF_REQUEST = "TIME_OFF_REQUEST";
    this.TIME_OFF_RULE = "TIME_OFF_RULE";
    this.TIME_OFF_TYPE = "TIME_OFF_TYPE";
    this.TIME_SHEET = "TIME_SHEET";
    this.TOPIC = "TOPIC";
    this.TRANSACTION = "TRANSACTION";
    this.TRANSFER_ORDER = "TRANSFER_ORDER";
    this.UBER = "UBER";
    this.UNITS_TYPE = "UNITS_TYPE";
    this.UNLOCKED_TIME_PERIOD = "UNLOCKED_TIME_PERIOD";
    this.USAGE = "USAGE";
    this.USEREVENT_SCRIPT = "USEREVENT_SCRIPT";
    this.VENDOR = "VENDOR";
    this.VENDOR_BILL = "VENDOR_BILL";
    this.VENDOR_CATEGORY = "VENDOR_CATEGORY";
    this.VENDOR_CREDIT = "VENDOR_CREDIT";
    this.VENDOR_PAYMENT = "VENDOR_PAYMENT";
    this.VENDOR_PREPAYMENT_APPLICATION = "VENDOR_PREPAYMENT_APPLICATION";
    this.VENDOR_RETURN_AUTHORIZATION = "VENDOR_RETURN_AUTHORIZATION";
    this.VENDOR_SUBSIDIARY_RELATIONSHIP = "VENDOR_SUBSIDIARY_RELATIONSHIP";
    this.WAVE = "WAVE";
    this.WBS = "WBS";
    this.WEBSITE = "WEBSITE";
    this.WORKFLOW_ACTION_SCRIPT = "WORKFLOW_ACTION_SCRIPT";
    this.WORK_ORDER = "WORK_ORDER";
    this.WORK_ORDER_CLOSE = "WORK_ORDER_CLOSE";
    this.WORK_ORDER_COMPLETION = "WORK_ORDER_COMPLETION";
    this.WORK_ORDER_ISSUE = "WORK_ORDER_ISSUE";
    this.WORKPLACE = "WORKPLACE";
    this.ZONE = "ZONE";
  }

  search.prototype.Operator = new Operator();

  search.prototype.Sort = new Sort();

  search.prototype.Summary = new Summary();

  search.prototype.Type = new Type();

  return new search();
})();